##! XSH module `PKGBUILD` package and build operations.
use pm.env as pm_env

## Exported declaration `name`.
export const name = "libdrm"

## Explicit payload or metapackage classification.
export const package_kind = "payload"

## Exported declaration `ver`.
export const ver = "2.4.134"

## Exported declaration `rel`.
export const rel = "1"

## Exported declaration `deps`.
export const deps = ["musl", "libudev-zero"]

## Exported declaration `mkdeps_host`.
export const mkdeps_host = ["llvm-toolchain", "linux-headers", "muon", "samurai", "pkgconf", "libudev-zero"]

## Exported declaration `upstream_sources`.
export const upstream_sources = [
  {
    source: p"https://dri.freedesktop.org/libdrm/libdrm-VERSION.tar.xz",
    kind: "auto",
    architectures: [
      "all",
    ],
    checksums: [
      {
        arch: "all",
        sha256: "ac5e74d157830eb8bee44c6a6bf3ad49774ef0dd2a72bdad74a8f20308b52a95",
      },
    ],
  },
]

type Modifier = {vendor: Str, mod: Str, name: Str}

## Exported declaration `filetree`.
export const filetree = [
  {
    path: p"usr/include/libdrm/amdgpu_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/drm_fourcc.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/drm_mode.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/drm_sarea.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/i915_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/mach64_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/mga_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/msm_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/nouveau_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/qxl_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/r128_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/radeon_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/savage_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/sis_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/tegra_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/vc4_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/via_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libdrm/virtgpu_drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/libsync.h",
    kind: "file",
  },
  {
    path: p"usr/include/xf86drm.h",
    kind: "file",
  },
  {
    path: p"usr/include/xf86drmMode.h",
    kind: "file",
  },
  {
    path: p"usr/lib/libdrm.so",
    kind: "symlink",
  },
  {
    path: p"usr/lib/libdrm.so.2",
    kind: "symlink",
  },
  {
    path: p"usr/lib/libdrm.so.2.134.0",
    kind: "binary",
  },
  {
    path: p"usr/lib/pkgconfig/libdrm.pc",
    kind: "file",
  },
]

# Port of gen_table_fourcc.py: the same three line patterns, applied per line
# (its trailing `\s` there matches the newline, hence `(\s|$)` here). Only the
# listed vendors get named modifier entries; the others, such as GENERIC and
# MTK, are left to libdrm's per-vendor name lookups.
proc write_format_modifier_table() {
  let header = p"include/drm/drm_fourcc.h"
  var intel = []
  var modifiers: List[Modifier] = []
  var vendors = []

  for line in header.read_text()?.split("\n") {
    if let [_, mod] = rx"^#define I915_FORMAT_MOD_(\w+)".captures(line) {
      intel += [mod]
    }

    if let [_, entry, _] = rx"^#define DRM_FORMAT_MOD_((?:ARM|APPLE|SAMSUNG|QCOM|VIVANTE|NVIDIA|BROADCOM|ALLWINNER)\w+)(\s|$)".captures(
      line,
    ) {
      if let [_, vendor, mod] = rx"^([^_]*)_(.*)$".captures(entry) {
        if ! (vendor == "ARM" and (mod == "TYPE_AFBC" or mod == "TYPE_MISC" or mod == "TYPE_AFRC")) {
          modifiers += [{vendor, mod, name: mod}]
        }
      }
    }

    if let [_, vendor] = rx"^#define DRM_FORMAT_MOD_VENDOR_(\w+)".captures(line) {
      vendors += [vendor]
    }
  }

  var body = [
    "/* AUTOMATICALLY GENERATED by the Laputa libdrm package. */",
    "static const struct drmFormatModifierInfo drm_format_modifier_table[] = {",
    "    { DRM_MODIFIER_INVALID(NONE, INVALID) },",
    "    { DRM_MODIFIER_LINEAR(NONE, LINEAR) },",
  ]

  for mod in intel {
    body += [f"    {{ DRM_MODIFIER_INTEL({mod}, {mod}) }},"]
  }

  for mod in modifiers {
    body += [f"    {{ DRM_MODIFIER({mod.vendor}, {mod.mod}, {mod.name}) }},"]
  }

  body += ["};"]
  body += ["static const struct drmFormatModifierVendorInfo drm_format_modifier_vendor_table[] = {"]

  for vendor in vendors {
    body += [f"    {{ DRM_FORMAT_MOD_VENDOR_{vendor}, \"{vendor}\" }},"]
  }

  body += ["};"]
  p"generated_static_table_fourcc.h".write(body.join("\n"))
}

proc patch_python_generator() {
  write_format_modifier_table()
  let meson = p"meson.build"
  var text = meson.read_text()?

  text = text.replace(
    """python3 = import('python').find_installation()
format_mod_static_table = custom_target(
  'format_mod_static_table',
  output : 'generated_static_table_fourcc.h',
  input : 'include/drm/drm_fourcc.h',
  command : [python3, files('gen_table_fourcc.py'), '@INPUT@', '@OUTPUT@'])
""",
    """format_mod_static_table = files('generated_static_table_fourcc.h')
""",
  )

  meson.write(text)
}

## Exported declaration `build`.
export proc build(dest: Path) [fs, process, env, error] {
  let muon = process.which("muon")?
  let jobs_flag = f"-j{cpu.count()}"
  let pc = pm_env.pkg_config_context()?
  patch_python_generator()

  env ({
    LD_LIBRARY_PATH: pc.ld_library_path,
    PKG_CONFIG: pc.pkg_config,
    PKG_CONFIG_LIBDIR: pc.pkg_config_libdir,
    PKG_CONFIG_PATH: pc.pkg_config_path,
    PKG_CONFIG_SYSROOT_DIR: pc.pkg_config_sysroot,
  }) {
    run $muon "setup" pm_env.meson_prefix_arg() pm_env.meson_libdir_arg() "-Ddefault_library=shared" "-Dudev=true" "-Dtests=false" "-Dinstall-test-programs=false" "-Dman-pages=disabled" "-Dvalgrind=disabled" "-Dcairo-tests=disabled" "-Dintel=disabled" "-Dradeon=disabled" "-Damdgpu=disabled" "-Dnouveau=disabled" "-Dvmwgfx=disabled" "-Domap=disabled" "-Dexynos=disabled" "-Dfreedreno=disabled" "-Dtegra=disabled" "-Dvc4=disabled" "-Detnaviv=disabled" "build"
    run $muon "-C" "build" samu $jobs_flag

    env ({
      DESTDIR: dest,
    }) {
      run $muon "-C" "build" install
    }
  }?
}
