# syntax=docker/dockerfile:1.4
ARG PACKAGE_TOOLS_IMAGE=laputa-bootstrapped-build-essential-native:latest
FROM ${PACKAGE_TOOLS_IMAGE} AS proof-rootfs-builder

WORKDIR /src
ENV XSH_MODULE_PATH=/usr/lib/pm
ENV XSH_PM_REPO=file:///src/target/repo

COPY --from=packages pm.xsh /usr/lib/pm/pm.xsh
COPY --from=packages pm/ /usr/lib/pm/pm/

COPY --from=packages repo/xsh/ packages/repo/xsh/
COPY --from=packages repo/xinit/ packages/repo/xinit/

COPY proof-rootfs.xsh proof-rootfs.xsh
COPY prepare-proof-rootfs-package-upgrade.xsh prepare-proof-rootfs-package-upgrade.xsh
COPY proof-stage.xsh proof-stage.xsh

RUN ["/bin/xsh", "/usr/lib/pm/pm.xsh", "--", \
    "download", "/rootfs", "/tmp/proof-rootfs-work", "/tmp/proof-rootfs-out", \
    "/src/packages/repo/xsh", "/src/packages/repo/xinit"]
RUN --network=none ["/bin/xsh", "prepare-proof-rootfs-package-upgrade.xsh", "--", "/rootfs", "/build-env"]
RUN --network=none ["/bin/xsh", "/usr/lib/pm/pm.xsh", "--", \
    "build-install", "/rootfs", "/build-env", "/tmp/proof-rootfs-work", "/tmp/proof-rootfs-out", \
    "/src/packages/repo/xsh", "/src/packages/repo/xinit"]
RUN --network=none ["/bin/xsh", "proof-rootfs.xsh", "--", "/rootfs"]

FROM scratch

COPY --from=proof-rootfs-builder /rootfs/ /

ENV XSH_LINUX_DRY_RUN=1
ENV XSH_LINUX_DRY_RUN_SIGNAL=TERM
ENV XSH_LINUX_DRY_RUN_LOG=/run/xsh-linux-dry-run.jsonl
ENV XSH_UNIX_DRY_RUN=1
ENV XSH_UNIX_DRY_RUN_SIGNAL=TERM
ENV XSH_UNIX_DRY_RUN_LOG=/run/xsh-unix-dry-run.jsonl
ENV XSH_XINIT_PROOF_STAGE=1
ENV PATH=/bin:/usr/bin

ENTRYPOINT ["/usr/bin/xinit", "/etc/inittab"]
