##! XSH module `linux_config` package and build operations.
use kbuild

proc resolved_fragment_input(input: Path) [fs, env, error] -> Result[Path] {
  let source_root = (e"XSH_PM_SOURCE_DIR" ?? "").trim()

  if source_root != "" {
    let staged = fp"{source_root}/.laputa-inputs/{input}"

    return staged when staged.exists()?
  }

  let recipe_root = (e"XSH_PM_RECIPE_DIR" ?? "").trim()

  if recipe_root != "" {
    let copied = fp"{recipe_root}/{input}"

    return copied when copied.exists()?
  }

  Err(
    kbuild.ScriptError.Failed(
      kind: "linux-config-fragment-missing",
      message: f"missing kernel config fragment {input} from staged source or typed recipe directory",
    ),
  )
}

## Resolves declared Linux config inputs from verified source staging or the copied typed recipe.
## It deliberately never interprets an input relative to the build process cwd.
export proc resolve_config_fragments(inputs: List[Path]) [fs, env, error] -> Result[List[Path], Error] {
  var fragments = [resolved_fragment_input(input)? for input in inputs]
  fragments
}

proc render_fragments(fragments: List[Path]) [fs, error] -> Result[Str] {
  var out = """# Generated by linux_config.xsh from package config fragments.
#
"""

  for fragment in fragments {
    guard fragment.exists()? else {
      return Err(
        kbuild.ScriptError.Failed(kind: "linux-config-fragment-missing", message: f"missing kernel config fragment {fragment}"),
      )
    }

    out = f"""{out}{fragment.read_text()?.trim()}
"""
  }

  out
}

## Exported declaration `write_resolved_config`.
export proc write_resolved_config(root: Path, srcarch: Str, fragments: List[Path], out: Path) [fs, error] {
  let _ = {root: root.display(), srcarch}
  kbuild.write_text_if_changed(out, render_fragments(fragments)?)?
}
