##! The one canonical Laputa graphical QEMU reference system profile.
use laputa.types as types

## The direct package intent for a real dwl and foot system; dependencies are resolved by PM.
export let profile: types.SystemProfile = {
  name: "qemu-dwl-foot",
  package_roots: [
    "baselayout",
    "xsh",
    "laputa-pm",
    "xinit",
    "mdevd",
    "seatd",
    "dwl-minimal",
    "foot-minimal",
  ],
  kernel_package: "linux",
  kernel_path: p"boot/vmlinuz",
  qemu_machine: "virt,accel=hvf,highmem=off",
  qemu_cpu: "host",
  qemu_smp: 2,
  qemu_memory: "1536M",
  qemu_width: 1280,
  qemu_height: 800,
  forbidden_packages: [
    "llvm-toolchain",
    "pkgconf",
    "cmake",
    "muon",
    "samurai",
    "m4",
    "flex",
    "bison",
    "wayland-dev",
    "wayland-protocols",
    "pixman-dev",
    "dbus",
    "systemd",
    "xwayland",
    "gtk",
    "pango",
    "pipewire",
    "pulseaudio",
    "python",
  ],
  forbidden_sonames: ["libLLVM", "libclang", "libpython", "libgtk", "libpango", "libpipewire", "libpulse"],
}
